from torchgeodemo import autoencoder_search

# Base configuration for the autoencoder
# these values will be the same for all configurations
ae_base = {
    'random_seed' : 20210321,
    'working_dir' : 'scratch',
    'data: source'       : 'example/example.csv',
    'data: nickname'     : 'example_geodemo',
    'data: id_col'       : 'ID',
    'data: exclude_cols' : ['CL'],
    'autoencoder: nickname'        : 'model_search',
    'autoencoder: save_latent'     : 'csv',
    'autoencoder: max_epochs'      : 10,
    'autoencoder: loader_workers'  : 11,
    'autoencoder: encoder: loss_weights: covariance' : 0.001
}

# Options for the autoencoder configurations
# Each configuration will be generated by combining 
# a prduct of each option proposed values 
# with the base configuration
ae_options = {
    'autoencoder: batch_size'     : [0.01, 0.005, 0.001],
    'autoencoder: encoder: sizes' : [[8, 4], [8, 4, 2]],
    'autoencoder: encoder: loss_weights: latent_l1' : [0.0, 0.01],
}

# Generate configurations based on the base and options
# and run the training
ae_final_report = autoencoder_search.explore_configs(ae_base, ae_options, state_subversion_of=1)
ae_final_report.to_csv('scratch/example_ae_search.csv', index=False)

