data:
  source:    'examples/example.csv'
  nickname:  'example_geodemo'
  id_col:    'ID'
  exclude_cols:
    - 'CL'
working_dir: 'scratch'
random_seed: 20210321
autoencoder:
  nickname:    'to4embk2_relu'
  version:     '0_1'
  save_latent: 'csv'
  max_epochs:  100
  batch_size:  0.01
  learning_rate:  1.0e-4
  encoder:
    sizes:
      - 8
      - 4
    activation:   'ReLU'
    sparse:
      topk_k:     2
      use_batch_norm: true
  loss_weights:
    latent_l0:    0.001
    auxk:         0.01
